# Generated by Django 5.2 on 2025-04-23 13:24

import auto_prefetch
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoundDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('doc_type', models.CharField(max_length=50)),
                ('delivery_place', models.CharField(max_length=50)),
                ('delivery_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('doc_ref_number', models.CharField(max_length=50)),
                ('doc_name', models.CharField(max_length=120)),
                ('doc_last_name', models.CharField(max_length=120)),
                ('doc_nick_name', models.CharField(blank=True, max_length=120, null=True)),
                ('doc_date_of_birth', models.DateField(blank=True, null=True)),
                ('doc_place_of_birth', models.CharField(blank=True, max_length=120, null=True)),
                ('doc_image_recto', models.ImageField(blank=True, null=True, upload_to='docs/lost')),
                ('doc_image_verso', models.ImageField(blank=True, null=True, upload_to='docs/lost')),
                ('doc_status', models.CharField(choices=[('L', 'Lost'), ('F', 'Found'), ('T', 'Taken')], max_length=1)),
                ('finding_commission', models.DecimalField(blank=True, decimal_places=3, max_digits=16)),
                ('founded_at', models.CharField(max_length=120)),
                ('picker_email', models.EmailField(max_length=120)),
                ('picker_number', models.IntegerField(max_length=14)),
                ('created_by', auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='LostDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('doc_type', models.CharField(max_length=50)),
                ('delivery_place', models.CharField(max_length=50)),
                ('delivery_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('doc_ref_number', models.CharField(max_length=50)),
                ('doc_name', models.CharField(max_length=120)),
                ('doc_last_name', models.CharField(max_length=120)),
                ('doc_nick_name', models.CharField(blank=True, max_length=120, null=True)),
                ('doc_date_of_birth', models.DateField(blank=True, null=True)),
                ('doc_place_of_birth', models.CharField(blank=True, max_length=120, null=True)),
                ('doc_image_recto', models.ImageField(blank=True, null=True, upload_to='docs/lost')),
                ('doc_image_verso', models.ImageField(blank=True, null=True, upload_to='docs/lost')),
                ('doc_status', models.CharField(choices=[('L', 'Lost'), ('F', 'Found'), ('T', 'Taken')], max_length=1)),
                ('finding_commission', models.DecimalField(blank=True, decimal_places=3, max_digits=16)),
                ('last_remembering_place', models.CharField(max_length=120)),
                ('picker_reward', models.TextField()),
                ('loser_email', models.EmailField(max_length=120)),
                ('loser_number', models.IntegerField(max_length=14)),
                ('created_by', auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
