# Generated by Django 5.2 on 2025-05-01 21:50

import auto_prefetch
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("finding_cost", models.DecimalField(decimal_places=3, max_digits=16)),
                (
                    "finding_commission",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=16),
                ),
                ("insurance_fees", models.DecimalField(decimal_places=3, max_digits=3)),
                ("lifetime", models.PositiveIntegerField()),
                (
                    "lifetime_unit",
                    models.CharField(
                        choices=[
                            ("D", "Days"),
                            ("W", "Weeks"),
                            ("M", "Months"),
                            ("Y", "Years"),
                        ],
                        default="Y",
                        max_length=1,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=3, max_digits=16)),
                (
                    "price_currency",
                    models.CharField(
                        choices=[("D", "Dollar"), ("B", "BIF"), ("C", "CDF")],
                        max_length=3,
                    ),
                ),
                (
                    "created_by",
                    auto_prefetch.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("created_at",),
                "abstract": False,
                "base_manager_name": "prefetch_manager",
                "default_manager_name": "objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="FoundDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "delivery_place",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("delivery_date", models.DateField(blank=True, null=True)),
                ("expiration_date", models.DateField(blank=True, null=True)),
                ("doc_ref_number", models.CharField(max_length=50)),
                ("doc_name", models.CharField(max_length=120)),
                ("doc_last_name", models.CharField(max_length=120)),
                (
                    "doc_nick_name",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("doc_date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "doc_place_of_birth",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "doc_image_recto",
                    models.ImageField(blank=True, null=True, upload_to="docs/lost"),
                ),
                (
                    "doc_image_verso",
                    models.ImageField(blank=True, null=True, upload_to="docs/lost"),
                ),
                (
                    "doc_status",
                    models.CharField(
                        choices=[
                            ("L", "Lost"),
                            ("P", "Picked_up"),
                            ("F", "Found"),
                            ("C", "Claimed"),
                            ("T", "Taken"),
                        ],
                        max_length=1,
                    ),
                ),
                ("founded_at", models.CharField(blank=True, max_length=120, null=True)),
                ("picker_email", models.EmailField(max_length=120)),
                ("picker_number", models.IntegerField()),
                (
                    "claimed_by",
                    models.EmailField(blank=True, max_length=120, null=True),
                ),
                (
                    "created_by",
                    auto_prefetch.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "doc_type",
                    auto_prefetch.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="document.documenttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
                "default_manager_name": "objects",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at", None)),
                        fields=("doc_type", "doc_name", "doc_last_name"),
                        name="issued_founddocuments",
                        violation_error_message="this document has already been issued",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at", None)),
                        fields=("doc_ref_number",),
                        name="unique_founddocuments_ref_number",
                        violation_error_message="a document with this ref number has already been issued",
                    ),
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="LostDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "delivery_place",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("delivery_date", models.DateField(blank=True, null=True)),
                ("expiration_date", models.DateField(blank=True, null=True)),
                ("doc_ref_number", models.CharField(max_length=50)),
                ("doc_name", models.CharField(max_length=120)),
                ("doc_last_name", models.CharField(max_length=120)),
                (
                    "doc_nick_name",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("doc_date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "doc_place_of_birth",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "doc_image_recto",
                    models.ImageField(blank=True, null=True, upload_to="docs/lost"),
                ),
                (
                    "doc_image_verso",
                    models.ImageField(blank=True, null=True, upload_to="docs/lost"),
                ),
                (
                    "doc_status",
                    models.CharField(
                        choices=[
                            ("L", "Lost"),
                            ("P", "Picked_up"),
                            ("F", "Found"),
                            ("C", "Claimed"),
                            ("T", "Taken"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "last_remembering_place",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("picker_reward", models.TextField(blank=True, null=True)),
                ("loser_email", models.EmailField(max_length=120)),
                ("loser_number", models.IntegerField()),
                ("found_by", models.EmailField(blank=True, max_length=120, null=True)),
                (
                    "created_by",
                    auto_prefetch.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "doc_type",
                    auto_prefetch.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)ss",
                        to="document.documenttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "prefetch_manager",
                "default_manager_name": "objects",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at", None)),
                        fields=("doc_type", "doc_name", "doc_last_name"),
                        name="issued_lostdocuments",
                        violation_error_message="this document has already been issued",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at", None)),
                        fields=("doc_ref_number",),
                        name="unique_lostdocuments_ref_number",
                        violation_error_message="a document with this ref number has already been issued",
                    ),
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
