# Generated by Django 5.2 on 2025-05-01 21:50

import auto_prefetch
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0001_initial"),
        ("insurance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lostdocument",
            name="loser_insurance",
            field=auto_prefetch.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lost_documents",
                to="insurance.lostdocumentinsurance",
            ),
        ),
    ]
