# Generated by Django 5.2 on 2025-05-02 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0002_lostdocument_loser_insurance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lostdocument",
            name="loser_insurance",
        ),
    ]
