# Generated by Django 5.2 on 2025-04-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="founddocument",
            name="picker_number",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="lostdocument",
            name="loser_number",
            field=models.IntegerField(),
        ),
    ]
