# Generated by Django 5.2 on 2025-05-02 08:40

import auto_prefetch
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0001_initial"),
        ("document", "0003_remove_lostdocument_loser_insurance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documenttype",
            name="price_currency",
            field=auto_prefetch.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="doc_types",
                to="config.currency",
            ),
        ),
    ]
