# Generated by Django 5.2 on 2025-04-23 15:26

import auto_prefetch
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_alter_founddocument_picker_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='founddocument',
            name='finding_commission',
        ),
        migrations.RemoveField(
            model_name='lostdocument',
            name='finding_commission',
        ),
        migrations.AlterField(
            model_name='founddocument',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='founddocument',
            name='delivery_place',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='founddocument',
            name='doc_status',
            field=models.CharField(choices=[('L', 'Lost'), ('F', 'Found'), ('I', 'Issued'), ('T', 'Taken')], max_length=1),
        ),
        migrations.AlterField(
            model_name='founddocument',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lostdocument',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lostdocument',
            name='delivery_place',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lostdocument',
            name='doc_status',
            field=models.CharField(choices=[('L', 'Lost'), ('F', 'Found'), ('I', 'Issued'), ('T', 'Taken')], max_length=1),
        ),
        migrations.AlterField(
            model_name='lostdocument',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lostdocument',
            name='last_remembering_place',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='lostdocument',
            name='picker_reward',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('name', models.CharField(max_length=120)),
                ('finding_cost', models.DecimalField(decimal_places=3, max_digits=16)),
                ('finding_commission', models.DecimalField(blank=True, decimal_places=3, max_digits=16)),
                ('created_by', auto_prefetch.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='founddocument',
            name='doc_type',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='document.documenttype'),
        ),
        migrations.AlterField(
            model_name='lostdocument',
            name='doc_type',
            field=auto_prefetch.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='document.documenttype'),
        ),
    ]
