# Generated by Django 5.2 on 2025-05-02 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0004_alter_documenttype_price_currency"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documenttype",
            name="insurance_fees",
        ),
    ]
