# Generated by Django 5.2 on 2025-04-23 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0004_remove_founddocument_finding_commission_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documenttype",
            name="name",
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
