# Generated by Django 5.2 on 2025-04-24 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0007_alter_founddocument_doc_ref_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="founddocument",
            name="doc_status",
            field=models.CharField(
                choices=[
                    ("L", "Lost"),
                    ("F", "Found"),
                    ("C", "Claimed"),
                    ("T", "Taken"),
                ],
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="lostdocument",
            name="doc_status",
            field=models.CharField(
                choices=[
                    ("L", "Lost"),
                    ("F", "Found"),
                    ("C", "Claimed"),
                    ("T", "Taken"),
                ],
                max_length=1,
            ),
        ),
    ]
