# Generated by Django 5.2 on 2025-04-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("document", "0008_alter_founddocument_doc_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="founddocument",
            name="claimed_by",
            field=models.EmailField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="lostdocument",
            name="found_by",
            field=models.EmailField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name="founddocument",
            name="doc_status",
            field=models.CharField(
                choices=[
                    ("L", "Lost"),
                    ("P", "Picked_up"),
                    ("D", "Droped_of"),
                    ("F", "Found"),
                    ("C", "Claimed"),
                    ("T", "Taken"),
                ],
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="lostdocument",
            name="doc_status",
            field=models.CharField(
                choices=[
                    ("L", "Lost"),
                    ("P", "Picked_up"),
                    ("D", "Droped_of"),
                    ("F", "Found"),
                    ("C", "Claimed"),
                    ("T", "Taken"),
                ],
                max_length=1,
            ),
        ),
    ]
