API_SUCCESS = "00"
API_GENERIC_ERROR = "01"

API_INVALID_PASSWORD = "02"

API_OBJECT_NOT_FOUND = "03"
API_INVALID_OBJECT = "04"
API_INSUFISCIENT_FOUND = "05"

API_USER_ONLY_AUTH = "06"
API_OBJECT_UPDATED = "07"
