# Generated by Django 5.2 on 2025-05-02 07:43

import auto_prefetch
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("insurance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insurancecard",
            name="lost_doc_insurance",
            field=auto_prefetch.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="card",
                to="insurance.lostdocumentinsurance",
            ),
        ),
    ]
